config/routes.rb
Rails.application.routes.draw do

  resources :commentaires, only: [:new, :create]
  get 'comments/success', to: 'commentaires#success', as: 'comment_success'
  get 'reservations/new'
  get 'reservations/confirm'
  get 'reservations/success'
  get 'services/index'

  devise_for :users
  root to: "pages#home"

  resources :reservations, only: [:new, :create]
  get 'reservations/confirm', to: 'reservations#confirm', as: 'confirm_reservations'
  get 'reservations/success', to: 'reservations#success', as: 'success_reservations'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
  belongs_to :user
  belongs_to :service
  validates :contenu, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :commentaires, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations, dependent: :destroy
  has_many :commentaires, dependent: :destroy
  validates :telephone, presence: true, format: { with: /\A6\d{8}\z/, message: "doit commencer par 6 et contenir exactement 9 chiffres" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nom, :telephone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nom, :telephone])
  end
end

app/controllers/commentaires_controller.rb
class CommentairesController < ApplicationController
  before_action :authenticate_user!

  def new
    @commentaire = Commentaire.new
  end

  def create
    @commentaire = Commentaire.new(commentaire_params)
    @commentaire.user = current_user
    if @commentaire.save
      CommentaireMailer.new_commentaire(@commentaire).deliver_now
      redirect_to comment_success_path
    else
      render :new
    end
  end

  def success
  end

  private

  def commentaire_params
    params.require(:commentaire).permit(:contenu, :service_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @services = Service.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.montant_a_payer = calculer_montant(@reservation)
    if @reservation.save
      ReservationMailer.new_reservation(@reservation).deliver_now
      redirect_to success_reservations_path
    else
      render :new
    end
  end

  def confirm
    # @reservation = Reservation.find(params[:id])
    # ReservationMailer.confirmation(@reservation).deliver_now
  end

  def success
  end

  private

  def calculer_montant(reservation)
    # Calcule la durée du séjour en jours (minimum 1 jour)
    duree_sejour = [(reservation.date_fin - reservation.date_debut).to_i, 1].max

    # Tarif journalier selon le service sélectionné
    tarif_journalier = case reservation.service_id
                       when Service.find_by(name: "Chambres haut standing").id
                         30_000
                       when Service.find_by(name: "Studios meublés").id
                         35_000
                       when Service.find_by(name: "Appartements meublés").id
                         45_000
                       else
                         0 # Si le service n'est pas reconnu
                       end

    # Montant total = tarif journalier * durée du séjour
    tarif_journalier * duree_sejour
  end

  def reservation_params
    params.require(:reservation).permit(:service_id, :date_debut, :date_fin, :nb_adulte, :nb_enfant, :montant_a_payer, :mode_paiement)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @services = Service.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/commentaires/new.html.erb
<div class="page-title">
  <h1>Laisse ton avis</h1>
</div>
<%= render "/shared/comment-form" %>

app/views/commentaires/success.html.erb
<%= render "/shared/notification-comment-card" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Residence Hoteliere Njiah Daah</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="icon" type="image/png" href="<%= asset_path 'user.png' %>">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/js/bootstrap.min.js"></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js'></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'cards', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'reservations', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <% if controller_name == 'pages' && action_name == 'home' %>
      <%= render "shared/home-header" %>
    <% end %>
    <div class="content-wrapper container">
      <%= yield %>
    </div>
    <%= render "shared/map" %>
    <%= render "shared/footer" %>
    <%#= render "shared/floating-button" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <h2 id="greetings-user">Bonjour <%= current_user ? current_user.nom : "Visiteur" %>! <i class="fa-sharp fa-solid fa-face-smile-wink"></i></h2>
  <h1 class="home-card">La reference</h1>
  <%= render "/shared/carousel-presentation-card" %>
  <h1 class="home-card">Nos Services</h1>
  <%= render "/shared/carousel-service-card" %>
  <h1 class="home-card">Plus</h1>
  <%= render "/shared/plus" %>
  <h1 class="home-card">Chambre</h1>
  <%= render "/shared/services-card" %>
  <h1 class="home-card">Informations</h1>
  <%= render "/shared/information-card" %>
</div>

app/views/reservations/confirm.html.erb
<h1>Reservations#confirm</h1>
<p>Find me in app/views/reservations/confirm.html.erb</p>

app/views/reservations/new.html.erb
<div class="page-title">
  <h1>Faire une reservation</h1>
</div>
<%= render "/shared/reservation-form" %>

app/views/reservations/success.html.erb
<%= render "/shared/notification-card" %>

app/views/services/index.html.erb
<div class="page-title">
  <h1>Nos services</h1>
</div>
<%= render "/shared/location" %>
<%= render "/shared/images" %>
<div class="comment">
  <h3>Découvrez nos services</h3>
  <p>Nous offrons des chambres de différents standings.</p>
  <p>Notre restaurant propose des mets d'ici et d'ailleurs pour le plus grand bien de vos papilles gustatives et un confort assuré.</p>
</div>
<%= render "/shared/services-card" %>

app/views/shared/_carousel-presentation-card.erb
<div class="card-container">
  <div class="card-container-top">
    <div class="image-card">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "carousel1.jpg", class: "d-block w-100", alt: "First slide" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "carousel2.jpg", class: "d-block w-100", alt: "First slide" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "carousel3.jpg", class: "d-block w-100", alt: "First slide" %>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="explanation">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, dolorum quae! Inventore unde molestias ipsa facilis. Omnis architecto incidunt perspiciatis.</p>
    </div>
  </div>
  <div class="card-container-bottom">
    <%= link_to "Faire une reservation", reservations_new_path, class: "btn btn-primary", id: "reserver" %>
  </div>
</div>

app/views/shared/_carousel-service-card.erb
<div class="card-container">
  <div class="card-container-top">
    <div class="image-card">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "service-traiter.jpg", class: "d-block w-100", alt: "First slide" %>
            <div class="carousel-caption d-block">
              <h5>Service Traiteur</h5>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "chambre.jpg", class: "d-block w-100", alt: "First slide" %>
            <div class="carousel-caption d-block">
              <h5>Sejour</h5>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "appartement.jpg", class: "d-block w-100", alt: "First slide" %>
            <div class="carousel-caption d-block">
              <h5>Appartement meublé</h5>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="explanation">
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat deleniti sint libero voluptates cupiditate aliquid incidunt cumque qui quas facere!</p>
    </div>
  </div>
  <div class="card-container-bottom">
    <%= link_to "Decouvre nos services", services_index_path, class: "btn btn-primary", id: "reserver" %>
  </div>
</div>

app/views/shared/_carousel-service-card.html.erb
<div class="card-container">
  <div class="card-container-top">
    <div class="image-card">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "service-traiter.jpg", class: "d-block w-100", alt: "First slide" %>
            <div class="carousel-caption d-block">
              <h5>Service Traiteur</h5>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "chambre.jpg", class: "d-block w-100", alt: "First slide" %>
            <div class="carousel-caption d-block">
              <h5>Sejour</h5>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "appartement.jpg", class: "d-block w-100", alt: "First slide" %>
            <div class="carousel-caption d-block">
              <h5>Appartement meublé</h5>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="explanation">
      <h2 class="card-title">Services Premium</h2>
      <div class="card-text"> La Résidence Hôtelière Njiah-Daah propose une gamme variée de services premium pour offrir une expérience inégalée : <br>
        <br>
        <b>Hébergement haut standing :</b> 21 chambres, 04 studios et 02 appartements meublés avec des équipements modernes, incluant des cuisines équipées et des salons confortables. <br>
        <br>
        <b>Restauration et traiteur :</b> Un restaurant spacieux de 50 places propose des mets issus des quatre aires culturelles du Cameroun, ainsi que des cuisines africaine, américaine et européenne. <br>
        <br>
        <b>Divertissement :</b> Un snack-bar élégant et convivial, avec un choix de boissons et de liqueurs de qualité. <br>
        <br>
        <b>Sécurité et confort :</b> Parking gardé 24h/24, vidéosurveillance, et petit-déjeuner continental inclus. <br>
        <br>
        Avec des options de réservation simplifiées (appel, WhatsApp, e-mail, réseaux sociaux), la résidence met tout en œuvre pour garantir une expérience personnalisée et mémorable. </div>
    </div>
  </div>
  <div class="card-container-bottom">
    <%= link_to "Decouvre nos services", services_index_path, class: "btn btn-primary", id: "reserver" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_home-header.html.erb
<div class="home-header">
  <div class="main-header">
    <p id="hotel-ranking">
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-regular fa-star"></i>
      <i class="fa-regular fa-star"></i>
    </p>
    <h2>Votre confort, notre satisfaction...  </h2>
    <%= link_to "Reserver", reservations_new_path, class: "btn btn-primary", id: "reserver" %>
  </div>
</div>

app/views/shared/_images.html.erb
<div id="carouselExampleIndicators" class="carousel slide images-card" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "carousel1.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel2.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel3.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "1.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "2.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "3.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "4.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "5.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "6.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "7.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "8.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "9.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "10.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "11.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "12.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "13.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "14.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "15.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "16.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "17.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "18.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "19.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "20.jpg", class: "d-block w-100", alt: "First slide" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_information-card.erb
<div class="information-container">
  <div class="text-side card-text">
    <h3 class="section-title">Dernières Actualités</h3>
    <div class="card-text">
      Restez informé avec nos dernières nouvelles et actualités. Découvrez les événements récents, les développements économiques, politiques et culturels qui façonnent notre monde.
    </div>
  </div>
  <div class="video-side">
    <%= video_tag "info-video.mp4", :size => "320x240", :controls => true , class:"video" %>
  </div>
</div>

app/views/shared/_map.html.erb
<div class="card-container">
  <div id="coordonnees">
    <div class="coordonnees-title">
      <h3 class="section-title">Contacts</h3>
    </div>
    <div class="coordonnees-contain">
      <div class="coordonnees-contain-left">
        <p><i class="fa-solid fa-location-dot"></i> Cameroun, Dschang, Groupement Foto, Apres le carrefour Albert Camus</p>
        <p><i class="fa-solid fa-envelope"></i> njiahdaah.hotel@gmail.com</p>
      </div>
      <div class="coordonnees-contain-right">
        <p><i class="fa-solid fa-phone-volume"></i> +237 699 32 58 93 - +237 675 72 15 84</p>
        <p><a href="https://wa.me/+237675721584" class="btn-whatsapp" target="_blank"><i class="fa-brands fa-square-whatsapp"></i> Clique ici et écris-nous sur WhatsApp</a></p>
      </div>
    </div>
  </div>
  <div id='map'></div>
</div>
<script>
  mapboxgl.accessToken = 'pk.eyJ1Ijoicmlib3QtZmxldXJ5MDkiLCJhIjoiY20zZGF4bnowMDFicDJycHp3Njg4dWtpNyJ9.4okW20O1i3JkgfgdDPQqrg'; // Remplacez par votre clé API Mapbox
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11', // Style de la carte
    center: [10.072236, 5.453019], // Coordonnées de l'hôtel (longitude, latitude)
    zoom: 15
  });

  var marker = new mapboxgl.Marker()
    .setLngLat([10.072236, 5.453019]) // Coordonnées de l'hôtel (longitude, latitude)
    .addTo(map);
</script>

app/views/shared/_navbar-menu.html.erb
<div class="offcanvas offcanvas-start navbar-menu" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header head-menu">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <i class="fa-solid fa-house"></i>
        <%= link_to "Accueil", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <i class="fa-solid fa-layer-group"></i>
        <%= link_to "Decouvre nos services", services_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <i class="fa-solid fa-check"></i>
        <%= link_to "Faire une reservation", reservations_new_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <i class="fa-solid fa-comment"></i>
        <%= link_to "Laisse ton avis", new_commentaire_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <i class="fa-solid fa-arrow-left"></i>
          <%= link_to "Sign out",destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <i class="fa-solid fa-arrow-right"></i>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid navbar-inside">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
      <i class="fa-solid fa-bars"></i>
    </button>
    <%= link_to root_path, class: "navbar-brand mx-auto" do %>
      <h1>Residence Hoteliere Njiah Daah</h1>
    <% end %>
    <%= image_tag "user.png", class: "avatar", alt: "avatar" %>
    <%= render "shared/navbar-menu" %>
  </div>
</nav>

app/views/shared/_product-card.html.erb
<div class="card-container">
  <div class="card card-infos">
    <%= link_to services_index_path do %>
      <%= image_tag "chambre.jpg", class: "d-block w-100", alt: "First slide" %>
    <% end %>
    <div class="card-body product-card">
      <div class="info-left">
        <h5 class="card-title">Voir nos chambres</h5>
        <p class="card-text">A partir de 5000 FCFA.</p>
      </div>
      <div class="info-right">
        <%= link_to "Reserver", reservations_new_path, class: "btn btn-primary", id: "reserver" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_services-card.html.erb
<div id="services">
  <% @services.each do |service| %>
    <div class="card-container">
      <div class="card card-infos">
        <%= link_to services_index_path do %>
          <div id="carousel-<%= service.id %>" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% if service.name == 'Chambres haut standing' %>
                <div class="carousel-item active">
                  <%= image_tag "img-ch1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "img-ch2.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "img-ch3.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "img-ch4.jpg", class: "d-block w-100", alt: service.name %>
                </div>
              <% elsif service.name == 'Studios meublés' %>
                <div class="carousel-item active">
                  <%= image_tag "studio1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "studio2.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "studio3.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "studio4.jpg", class: "d-block w-100", alt: service.name %>
                </div>
              <% elsif service.name == 'Appartements meublés' %>
                <div class="carousel-item active">
                  <%= image_tag "studio1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "studio2.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "studio3.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "studio4.jpg", class: "d-block w-100", alt: service.name %>
                </div>
              <% else %>
                <div class="carousel-item active">
                  <%= image_tag "img-ch1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "img-ch1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "img-ch1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
                <div class="carousel-item">
                  <%= image_tag "img-ch1.jpg", class: "d-block w-100", alt: service.name %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carousel-<%= service.id %>" role="button" data-bs-slide="prev">
              <span class="carousel-control-prev-icon icon-direct" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-<%= service.id %>" role="button" data-bs-slide="next">
              <span class="carousel-control-next-icon icon-direct" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        <% end %>
        <div class="card-body product-card">
          <div class="info-left">
            <h5 class="card-title"><%= service.name %></h5>
            <p class="card-text"><%= service.description %></p>
            <% if service.name == 'Chambres haut standing' %>
              <p class="card-text"><span>A partir de 30.000 FCFA.</span></p>
            <% elsif service.name == 'Studios meublés' %>
              <p class="card-text"><span>A partir de 35.000 FCFA.</span></p>
            <% elsif service.name == 'Appartements meublés' %>
              <p class="card-text"><span>A partir de 45.000 FCFA.</span></p>
            <% else %>
              <p class="card-text"><span>Contacte nous pour plus d'informations.</span></p>
            <% end %>
          </div>
          <div class="info-right">
            <%= link_to "Reserver", reservations_new_path(service_id: service.id), class: "btn btn-primary", id: "reserver" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>